apiVersion: v1
kind: Namespace
metadata:
  name: kinesis-consumer-namespace
  labels:
    eventing.knative.dev/injection: enabled
    
---

apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: kinesis-consumer-broker
  namespace: kinesis-consumer-namespace
  
---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kinesis-knative-eventer
  namespace: kinesis-consumer-namespace
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "5"
        autoscaling.knative.dev/initial-scale: "0"
        autoscaling.knative.dev/min-scale: "2"
        autoscaling.knative.dev/max-scale: "20"
      labels:
        app: kinesis-knative-eventer
    spec:
      containerConcurrency: 10
      containers:
        - name: kinesis-knative-eventer
          image: 771830474512.dkr.ecr.us-east-1.amazonaws.com/kinesis-knative-ingest:latest
          ports:
            - containerPort: 443
              protocol: TCP
          env:
          - name: DATA_STREAM
            # TODO: Inject the correct value here on deployment
            # Ideally this would be mutli-tenent aware with each user/account
            # having their OWN stream OR the data stream having user aware things
            value: "test-data-stream"
          - name: AWS_DEFAULT_REGION
            value: "us-east-1"
          command: ["python3"]
          args: ["/app/ingest.py"]

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-sink
  namespace: kinesis-consumer-namespace
spec:
  template:
    metadata:
      labels:
        app: video-sink
    spec:
      containers:
        - name: video-sink
          image: 771830474512.dkr.ecr.us-east-1.amazonaws.com/video-consumer-knative-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 443
              protocol: TCP

---

apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kinesis-events-trigger
  namespace: kinesis-consumer-namespace
  annotations:
    knative-eventing-injection: enabled
spec:
  broker: kinesis-consumer-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: video-sink

---

apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-kinesis-sink
  namespace: kinesis-consumer-namespace
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: kinesis-knative-eventer
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: kinesis-consumer-broker